# Generated by s1's scripts/publish-tap.sh — regenerate, don't hand-edit.
cask "s1" do
  version "0.3.21"
  sha256 "33c8aa38a8f5b07634940ad0ac44e16ffb5ecf0b5ddee07128f02a784b9dd83a"

  url "https://github.com/Matthew-Eucaristo/s1/releases/download/v0.3.21/S1-#{version}-app.zip"
  name "s1"
  desc "Voice-first agent — menu-bar companion (System 1 + System 2), CLI included"
  homepage "https://github.com/Matthew-Eucaristo/s1"

  depends_on macos: :tahoe

  app "S1.app"
  # The CLI ships inside the bundle (Contents/Resources/s1) — brew links it
  # into HOMEBREW_PREFIX/bin so `s1` works on PATH from the same install.
  binary "#{appdir}/S1.app/Contents/Resources/s1"
  uninstall launchctl: ["com.matthew.s1.serve", "sh.brew.s1"],
            quit:      ["com.mattheweuc.s1", "com.matthew.s1.app"]

  zap trash: [
    "~/.s1",
    "~/Library/Application Scripts/com.mattheweuc.s1",
    "~/Library/Application Scripts/com.matthew.s1.app",
    "~/Library/Containers/com.mattheweuc.s1",
    "~/Library/Containers/com.matthew.s1.app",
    "~/Library/HTTPStorages/com.mattheweuc.s1",
    "~/Library/HTTPStorages/com.matthew.s1.app",
    "~/Library/LaunchAgents/com.matthew.s1.serve.plist",
    "~/Library/LaunchAgents/sh.brew.s1.plist",
    "~/Library/Preferences/com.mattheweuc.s1.plist",
    "~/Library/Preferences/com.matthew.s1.app.plist",
    "~/Library/Saved Application State/com.mattheweuc.s1.savedState",
    "~/Library/Saved Application State/com.matthew.s1.app.savedState",
  ]

  caveats <<~EOS
    Developer-signed but not notarized → Gatekeeper will block the first
    open. Either install with `brew install --cask --no-quarantine s1`,
    or once:
      xattr -dr com.apple.quarantine /Applications/S1.app
    Then open S1 and grant Accessibility + Screen Recording + Microphone
    when it asks — `s1 preflight` shows the score.

      Always-on listener:        s1 serve --install   (launchd agent, armed at login)
      Local model brain:         brew install ollama && ollama pull gemma3:4b
      Full reset:                brew uninstall --cask s1 --zap
  EOS
end
